# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initializeTerms <- function(X, neg_offset, max_vars) {
    .Call('_BITS_initializeTerms', PACKAGE = 'BITS', X, neg_offset, max_vars)
}

completeSearch <- function(X, y, neg_offset, max_vars, gamma, set_vars_R, reuse_terms, max_iter, force_model, adjust_shady_int = TRUE) {
    .Call('_BITS_completeSearch', PACKAGE = 'BITS', X, y, neg_offset, max_vars, gamma, set_vars_R, reuse_terms, max_iter, force_model, adjust_shady_int)
}

memoryTest <- function() {
    .Call('_BITS_memoryTest', PACKAGE = 'BITS')
}

customLm <- function(Xr, yr) {
    .Call('_BITS_customLm', PACKAGE = 'BITS', Xr, yr)
}

matrixVectorMult <- function(Z, y) {
    .Call('_BITS_matrixVectorMult', PACKAGE = 'BITS', Z, y)
}

matrixMatrixMult <- function(Z, Y) {
    .Call('_BITS_matrixMatrixMult', PACKAGE = 'BITS', Z, Y)
}

